using DevExpress.XtraBars;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using Ebda3Soft.Core;
using Ebda3Soft.Core.Database.Interfaces;
using Ebda3Soft.Core.Database.Entities.Financial;
using DevExpress.XtraBars.Docking2010.Customization;
using Ebda3Soft.Core.Database;

namespace Ebda3Soft.Views.UserControls.Financial
{
    public partial class AccountTypeCollectionView : DevExpress.XtraEditors.XtraUserControl, ISupportCollectionActions
    {
        SQLServerDbContext dbContext;
        public AccountTypeCollectionView()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            dbContext = SQLServerDbContext.Instance;

            RefreshData();
        }
        void bbiPrintPreview_ItemClick(object sender, ItemClickEventArgs e)
        {
            gridControl.ShowRibbonPrintPreview();
        }

        private void bbiNew_ItemClick(object sender, ItemClickEventArgs e)
        {
            New();
        }

        private void gridView_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            if (e.Clicks == 2)
            {
                Edit();
            }
        }

        public void New()
        {
            SharedView.ShowUserControlForm(new AccountTypeView(bindingSource, Ebda3Soft.Core.Enums.TransactionType.Adding));
        }

        public void Delete()
        {
            var entity = gridView.GetFocusedRow() as BaseEntity;
            if (entity != null)
            {
                if (entity.BindingSource == null)
                    entity.BindingSource = new BindingSource(bindingSource, "");
                entity.BindingSource.Position = bindingSource.Position;
                entity.Delete();
            }
        }

        public bool IsReadyToEdit()
        {
            return gridView.GetFocusedRow() != null;
        }
        public void Edit()
        {
            if (IsReadyToEdit())
                SharedView.ShowUserControlForm(new AccountTypeView(bindingSource, Ebda3Soft.Core.Enums.TransactionType.Modifying));
        }

        private void AccountTypeCollectionView_Load(object sender, EventArgs e)
        {
            bbiDelete.ItemClick += (o, ev) => Delete();
            bbiNew.ItemClick += (o, ev) => New();
            bbiEdit.ItemClick += (o, ev) => Edit();
            bbiRefresh.ItemClick += (o, ev) => RefreshData();
            gridView.RowClick += (o, ev) =>
            {
                if (ev.Clicks == 2)
                    Edit();
            };
        }

        public void RefreshData()
        {
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.AccountTypes.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                bindingSource.DataSource = dbContext.AccountTypes.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        public bool IsReadyToDelete()
        {
            return true;
        }
    }
}
