using DevExpress.XtraBars;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using Ebda3Soft.Core.Database.Interfaces;
using Ebda3Soft.Core;
using Ebda3Soft.Core.Database;
using DevExpress.XtraBars.Docking2010.Customization;

namespace Ebda3Soft.Views.UserControls.Financial
{
    public partial class CurrencyCollectionView : DevExpress.XtraEditors.XtraUserControl,ISupportCollectionActions
    {
        SQLServerDbContext dbContext;
        public CurrencyCollectionView()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            dbContext = SQLServerDbContext.Instance;
            RefreshData();            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
           
        }
        void bbiPrintPreview_ItemClick(object sender, ItemClickEventArgs e)
        {
            gridControl.ShowRibbonPrintPreview();
        }

        private void CurrencyCollectionView_Load(object sender, EventArgs e)
        {
            bbiDelete.ItemClick += (o, ev) => Delete();
            bbiNew.ItemClick += (o, ev) => New();
            bbiEdit.ItemClick += (o, ev) => Edit();
            bbiRefresh.ItemClick += (o, ev) => RefreshData();
            gridView.RowClick += (o, ev) =>
            {
                if (ev.Clicks == 2)
                    Edit();
            };
        }
        public void RefreshData()
        {
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Currencies.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                bindingSource.DataSource = dbContext.Currencies.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        private void bbiNew_ItemClick(object sender, ItemClickEventArgs e)
        {
            New();
        }


        public void New()
        {
            SharedView.ShowUserControlForm(new CurrencyView(bindingSource, Ebda3Soft.Core.Enums.TransactionType.Adding));
        }

        public void Delete()
        {
            var entity = gridView.GetFocusedRow() as BaseEntity;
            if (entity != null)
            {
                if (entity.BindingSource == null)
                    entity.BindingSource = new BindingSource(bindingSource, "");
                entity.BindingSource.Position = bindingSource.Position;
                entity.Delete();
            }
        }


        public bool IsReadyToEdit()
        {
            return gridView.GetFocusedRow() != null;
        }
        public void Edit()
        {
            if (IsReadyToEdit())
                SharedView.ShowUserControlForm(new CurrencyView(bindingSource, Ebda3Soft.Core.Enums.TransactionType.Modifying));
        }

        public bool IsReadyToDelete()
        {
            return true;
        }
    }
}
